# This is a combination of 46 commits. # This is the 1st commit message:
rtmp-services: add showroom setting

# This is the commit message #2:

rtmp-services: Modify showroom setting

Change recommend format and url.
Extend curl Timeout span.

# This is the commit message #3:

rtmp-services: remove unused code

# This is the commit message #4:

rtmp-services: showroom support autoconfig ui

# This is the commit message #5:

rtmp-services: clang format

# This is the commit message #6:

rtmp-services: Add WASDTV (#2697)


# This is the commit message #7:

CI: Add freetype dep on osx


# This is the commit message #8:

libobs: Fix plugin folder search path case on macOS

# This is the commit message #9:

linux-v4l2: Fix build with Clang 10.0

add_control_property() was previously static inline bool, but did not
return a value and failed to build on FreeBSD-CURRENT with Clang 10.0,
with:

error: non-void function 'add_control_property' should return a value

# This is the commit message #10:

CI: Add qt5-xml package for FreeBSD build task

# This is the commit message #11:

rtmp-services: Update ChathostessModels service (#2745)


# This is the commit message #12:

libobs: Don't save removed sources

# This is the commit message #13:

obs-ffmpeg: Fix media source not closing file when inactive

# This is the commit message #14:

obs-browser: Fix formatting

# This is the commit message #15:

obs-vst: Fix formatting

# This is the commit message #16:

obs-qsv11: Enable QSV texture-based encoding

Enables a pipeline for texture-based encoding with QSV. Utilizes OBS
NV12 output for encode to avoid offloading them from GPU, which will
increase performance. The option to select old QSV pipeline still
remains and will fallback if new pipeline fails.

# This is the commit message #17:

UI: Remove all scenes in ClearSceneData

# This is the commit message #18:

UI: Fix previewLabel styling

Label renders with default styling instead of using dynamic property
because it was already polished.

# This is the commit message #19:

docs/sphinx: Add Property Grouping

# This is the commit message #20:

plugins: Build ALSA plugin for FreeBSD

Signed-off-by: Hans Petter Selasky <hps@selasky.org>

# This is the commit message #21:

UI: Adjust a few margins

-Remove 9px margins around central widget. This saves 18px of vertical
space. This will be helpful when the source context menu is added,
which is 24px tall.

-Adjusts margins in transitions dock. The top of the transitions dock
wasn't lined up with the top of the controls dock, which made it look
bad.

# This is the commit message #22:

UI: Add status icons for recording and streaming

# This is the commit message #23:

CMake: Build Windows modules with file descriptors

# This is the commit message #24:

mac-capture: Use window id to identify windows on MacOS

Use a window's window id in init_window in the mac window capture plugin.

# This is the commit message #25:

mac-capture: Only find window by window id when owner name and pid match

# This is the commit message #26:

mac-capture: Use int in place of NSNumber for owner_pid

# This is the commit message #27:

mac-capture: update owner_pid in `update_window`

# This is the commit message #28:

CI: Add main Github Actions workflow for branch pushes and PRs

# This is the commit message #29:

UI: Remove unnecessary global variables

# This is the commit message #30:

Revert "UI: Remove unnecessary global variables"

This reverts commit f91d3baf43e69f6d1922b0e03e043af6de0baf6a.

From @pkv: the reason some of these vars were global is because Qt was not deleting them at all; as a result memory leaks have been reintroduced for: previewProjector, trayMenu, studioProgramProjector, multiviewProjectorMenu ;

# This is the commit message #31:

libobs-opengl: Fix viewport flip

Flip viewport in coordination with update_viewproj_matrix.

# This is the commit message #32:

UI: Add white icons for dock titles

- Add pop-out and close svg icons
- Update all dark themes qss with the new icons

# This is the commit message #33:

rtmp-services: Change Stripchat streaming service

# This is the commit message #34:

rtmp-services: Add VirtWish service

# This is the commit message #35:

UI: Update OSX to macOS in English translation

# This is the commit message #36:

obs-browser, obs-vst: Fix formatting

# This is the commit message #37:

CI: Fix Azure Pipelines macOS runs

# This is the commit message #38:

obs-filters: Add a user label to the LUT filter

While discussing the Flatpak RFC [1], it was spotted that the
LUT filter couldn't open the file selection dialog. It was
explained, then, that the proper formats were either composed
of "User Label (file extensions)", or "file extensions", and
the LUT filter was setting "(file extensions)" without the
actual user label.

While this works on a standard Qt file selection dialog, it
cannot be properly formatted as a set of D-Bus filters, thus
breaking the sandbox integration.

Add a simple user label to the LUT file filter.

[1] https://github.com/obsproject/rfcs/pull/21#issuecomment-619106757

# This is the commit message #39:

UI: Remove requirement for replay buffer hotkey

Fixes https://github.com/obsproject/obs-studio/issues/2807

# This is the commit message #40:

obs-ffmpeg: Log why new NVENC might not be used

# This is the commit message #41:

obs-ffmpeg: Preserve error message from new NVENC

If we fallback to ffmpeg NVENC, the error from new NVENC might still be
present in the encoder structure. Given that this provides a lot more
actionable information to the user, let's use it if possible.

# This is the commit message #42:

libobs: Clear last error on encoder shutdown

This fixes an issue where an encoder may error out on a path that
doesn't use obs_encoder_set_last_error, resulting in a stale error being
used.

# This is the commit message #43:

obs-ffmpeg: Add localization for NVENC error messages

# This is the commit message #44:

obs-ffmpeg: Add error message for non-zero GPU

# This is the commit message #45:

CI: Update macOS deps to fix lua

# This is the commit message #46:

vlc-video: Enable building the plugin on FreeBSD